# Generated by Django 2.1.5 on 2019-02-07 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0002_ride_request_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_request',
            name='Other_request',
            field=models.CharField(blank=True, choices=[('p', 'pets friendly'), ('s', 'smoke free'), ('w', 'wheelchair'), ('b', 'provide beverage')], help_text='Optional', max_length=256),
        ),
    ]
