# Generated by Django 2.1.5 on 2019-02-04 03:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ride_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriveTime', models.TimeField()),
                ('Destination', models.CharField(max_length=256)),
                ('PassageNum', models.PositiveSmallIntegerField(verbose_name='Passger Number')),
                ('Vehicle_type', models.CharField(blank=True, choices=[('v', 'volvo'), ('a', 'audi'), ('m', 'mercedes'), ('t', 'toyota'), ('h', 'honda'), ('n', 'nissan'), ('o', 'other')], max_length=256)),
                ('Share', models.BooleanField()),
                ('Other_request', models.CharField(blank=True, max_length=256)),
                ('ride_status', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Confirmed'), ('F', 'Finished')], default='O', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
