# Generated by Django 2.1.5 on 2019-02-07 01:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ride_request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arriveTime', models.CharField(help_text='Time Form: xx:xx ', max_length=256)),
                ('Destination', models.CharField(max_length=256)),
                ('PassageNum', models.PositiveSmallIntegerField(verbose_name='Passger Number')),
                ('Vehicle_type', models.CharField(blank=True, choices=[('v', 'volvo'), ('a', 'audi'), ('m', 'mercedes'), ('t', 'toyota'), ('h', 'honda'), ('n', 'nissan'), ('o', 'other')], help_text='Optional', max_length=256)),
                ('Share', models.BooleanField()),
                ('Other_request', models.CharField(blank=True, choices=[('b', 'big'), ('m', 'medium'), ('l', 'large')], help_text='Optional', max_length=256)),
                ('ride_status', models.CharField(blank=True, choices=[('O', 'Open'), ('C', 'Confirmed'), ('F', 'Finished')], default='O', max_length=200)),
                ('driver', models.CharField(blank=True, max_length=200)),
                ('vehicle', models.CharField(blank=True, max_length=200)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('plate', models.CharField(blank=True, max_length=200)),
                ('info', models.CharField(blank=True, max_length=200)),
                ('owner', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='rider_pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_request.ride_request')),
            ],
        ),
    ]
