# Generated by Django 2.1.5 on 2019-02-04 21:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ride_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
