# Generated by Django 2.1.5 on 2019-02-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_request',
            name='arriveTime',
            field=models.CharField(help_text='Time form: xx:xx p.m/a.m', max_length=256),
        ),
    ]
