# Generated by Django 2.1.5 on 2019-02-06 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0002_ride_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride_request',
            name='capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='driver',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='plate',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='ride_request',
            name='vehicle',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='Other_request',
            field=models.CharField(blank=True, choices=[('b', 'big'), ('m', 'medium'), ('l', 'large')], help_text='Optional', max_length=256),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='Vehicle_type',
            field=models.CharField(blank=True, choices=[('v', 'volvo'), ('a', 'audi'), ('m', 'mercedes'), ('t', 'toyota'), ('h', 'honda'), ('n', 'nissan'), ('o', 'other')], help_text='Optional', max_length=256),
        ),
        migrations.AlterField(
            model_name='ride_request',
            name='arriveTime',
            field=models.CharField(help_text='Time Form: xx:xx ', max_length=256),
        ),
    ]
