# Generated by Django 2.1.5 on 2019-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0003_auto_20190205_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='rider_pair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=200)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ride_request.ride_request')),
            ],
        ),
    ]
