# Generated by Django 2.1.5 on 2019-02-06 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0004_rider_pair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_request',
            name='arriveTime',
            field=models.TimeField(help_text='Time Form: xx:xx '),
        ),
    ]
