# Generated by Django 2.1.5 on 2019-02-06 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ride_request', '0005_auto_20190206_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride_request',
            name='arriveTime',
            field=models.CharField(help_text='Time Form: xx:xx ', max_length=256),
        ),
    ]
